name: Build site
on: push
jobs:
  main:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
         cd docs
         echo "Switched dir"
         pip install markdown pygments
         python md.py
